import _, { groupBy } from "lodash";
import Head from "next/head";
import React, { useEffect, useMemo } from "react";
import styles from "../../styles/SearchPage.module.scss";
import { withLayout } from "../../components/layout/Layout";
import { useRouter } from "next/router";
import { Htag } from "../../components/Htag";
import { useDispatch, useSelector } from "react-redux";
import { findProductsByText, findTopPageByText } from "../../redux/searchSlice";
import { RootState } from "../../redux/store";
import { Card } from "../../components/Card";
import { Tag } from "../../components/Tag";
import { Button } from "../../components/Button";
import { Paragraph } from "../../components/Paragraph";
import { motion } from "framer-motion";

const Page: React.FC = (props) => {
  const router = useRouter();
  const dispatch = useDispatch();

  const pages = useSelector((state: RootState) => state.search.topPages);

  useEffect(() => {
    if (router.query.q) {
      dispatch(findTopPageByText(router.query.q as string));
    }
  }, [router.query]);

  const goToPage = (alias: string) => {
    router.push({
      pathname: `topPages/${alias}`,
    });
  };

  return (
    <motion.div initial="initial" animate="enter" exit="exit" variants={{ exit: { transition: { opacity: 0 } } }} className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.head}>
          <div className={styles.icon}></div>
          <Htag className={styles.pageTitle} tag="h1">
            Поиск
          </Htag>
        </div>
        <Paragraph size="l">
          {"По запросу "}
          <strong>{`${router.query.q} `}</strong>
          найдено
          <strong>{`${pages.length} `}</strong>
          страниц
        </Paragraph>
        <div className={styles.content}>
          {pages.map((item) => (
            <Card key={item.id} className={styles.searchPageCard}>
              <Paragraph size="l" className={styles.title}>
                {item.title}
              </Paragraph>
              <Tag size="m" color="ghost">
                {item.secondCategory}
              </Tag>
              <Button appearance="primary" onClick={() => goToPage(item.alias)}>
                Перейти
              </Button>
            </Card>
          ))}
        </div>
      </main>
    </motion.div>
  );
};

export default withLayout(Page);
